/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TvseriesImport } from './routes/tvseries'
import { Route as MoviesImport } from './routes/movies'
import { Route as LoginImport } from './routes/login'
import { Route as HomeImport } from './routes/home'
import { Route as BookmarkedImport } from './routes/bookmarked'

// Create/Update Routes

const TvseriesRoute = TvseriesImport.update({
  id: '/tvseries',
  path: '/tvseries',
  getParentRoute: () => rootRoute,
} as any)

const MoviesRoute = MoviesImport.update({
  id: '/movies',
  path: '/movies',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const HomeRoute = HomeImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRoute,
} as any)

const BookmarkedRoute = BookmarkedImport.update({
  id: '/bookmarked',
  path: '/bookmarked',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/bookmarked': {
      id: '/bookmarked'
      path: '/bookmarked'
      fullPath: '/bookmarked'
      preLoaderRoute: typeof BookmarkedImport
      parentRoute: typeof rootRoute
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/movies': {
      id: '/movies'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof MoviesImport
      parentRoute: typeof rootRoute
    }
    '/tvseries': {
      id: '/tvseries'
      path: '/tvseries'
      fullPath: '/tvseries'
      preLoaderRoute: typeof TvseriesImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/bookmarked': typeof BookmarkedRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/movies': typeof MoviesRoute
  '/tvseries': typeof TvseriesRoute
}

export interface FileRoutesByTo {
  '/bookmarked': typeof BookmarkedRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/movies': typeof MoviesRoute
  '/tvseries': typeof TvseriesRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/bookmarked': typeof BookmarkedRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/movies': typeof MoviesRoute
  '/tvseries': typeof TvseriesRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/bookmarked' | '/home' | '/login' | '/movies' | '/tvseries'
  fileRoutesByTo: FileRoutesByTo
  to: '/bookmarked' | '/home' | '/login' | '/movies' | '/tvseries'
  id: '__root__' | '/bookmarked' | '/home' | '/login' | '/movies' | '/tvseries'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  BookmarkedRoute: typeof BookmarkedRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  MoviesRoute: typeof MoviesRoute
  TvseriesRoute: typeof TvseriesRoute
}

const rootRouteChildren: RootRouteChildren = {
  BookmarkedRoute: BookmarkedRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  MoviesRoute: MoviesRoute,
  TvseriesRoute: TvseriesRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/bookmarked",
        "/home",
        "/login",
        "/movies",
        "/tvseries"
      ]
    },
    "/bookmarked": {
      "filePath": "bookmarked.tsx"
    },
    "/home": {
      "filePath": "home.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/movies": {
      "filePath": "movies.tsx"
    },
    "/tvseries": {
      "filePath": "tvseries.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
