/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TvseriesImport } from './routes/tvseries'
import { Route as MoviesImport } from './routes/movies'
import { Route as LoginImport } from './routes/login'
import { Route as BookmarkedImport } from './routes/bookmarked'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const TvseriesRoute = TvseriesImport.update({
  id: '/tvseries',
  path: '/tvseries',
  getParentRoute: () => rootRoute,
} as any)

const MoviesRoute = MoviesImport.update({
  id: '/movies',
  path: '/movies',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const BookmarkedRoute = BookmarkedImport.update({
  id: '/bookmarked',
  path: '/bookmarked',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/bookmarked': {
      id: '/bookmarked'
      path: '/bookmarked'
      fullPath: '/bookmarked'
      preLoaderRoute: typeof BookmarkedImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/movies': {
      id: '/movies'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof MoviesImport
      parentRoute: typeof rootRoute
    }
    '/tvseries': {
      id: '/tvseries'
      path: '/tvseries'
      fullPath: '/tvseries'
      preLoaderRoute: typeof TvseriesImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bookmarked': typeof BookmarkedRoute
  '/login': typeof LoginRoute
  '/movies': typeof MoviesRoute
  '/tvseries': typeof TvseriesRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bookmarked': typeof BookmarkedRoute
  '/login': typeof LoginRoute
  '/movies': typeof MoviesRoute
  '/tvseries': typeof TvseriesRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/bookmarked': typeof BookmarkedRoute
  '/login': typeof LoginRoute
  '/movies': typeof MoviesRoute
  '/tvseries': typeof TvseriesRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bookmarked' | '/login' | '/movies' | '/tvseries'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bookmarked' | '/login' | '/movies' | '/tvseries'
  id: '__root__' | '/' | '/bookmarked' | '/login' | '/movies' | '/tvseries'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookmarkedRoute: typeof BookmarkedRoute
  LoginRoute: typeof LoginRoute
  MoviesRoute: typeof MoviesRoute
  TvseriesRoute: typeof TvseriesRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookmarkedRoute: BookmarkedRoute,
  LoginRoute: LoginRoute,
  MoviesRoute: MoviesRoute,
  TvseriesRoute: TvseriesRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/bookmarked",
        "/login",
        "/movies",
        "/tvseries"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/bookmarked": {
      "filePath": "bookmarked.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/movies": {
      "filePath": "movies.tsx"
    },
    "/tvseries": {
      "filePath": "tvseries.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
